config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
   
  get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  patch "/blog_posts/:id", to: "blog_posts#update"
  delete "/blog_posts/:id", to: "blog_posts#destroy"
  get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  # Defines the root path route ("/")
   root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true



  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
   before_action :set_blog_post, except: [:index, :new, :create]
  def index
    @blog_posts = BlogPost.all
  end

  def show
  
  end
  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to blog_post_path(@blog_post)
    else
      render :new, status: :unprocessable_entity
    end
  end

 def edit
  
  end 

  def update

    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path(@blog_post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

    @blog_post.destroy
    redirect_to root_path
  end

  private 

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "Blog post not found" 
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path, alert: "You need to sign in to access this page."    
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post, local: true do |form| %>
<% if @blog_post.errors.any? %>
  <div>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.submit "Edit" %>
<% end %>   

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>
<%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/blog_posts/index.html.erb
<h1 class="text-2xl font-bold mb-4 ">Blog Posts</h1>

<% @blog_posts.each do |blog_post|%>
<div class="blog-post">
<h2><%= link_to blog_post.title, blog_post_path(blog_post)%></h2>
<p><%=blog_post.body%></p>
</div>
<%end%>

app/views/blog_posts/new.html.erb
<h1>NEW Blog Post page </h1>



<%= form_with model: @blog_post, local: true do |form| %>
<% if @blog_post.errors.any? %>
  <div>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.submit "create Blog Post", class: "bg-gray-100 px-4 py-2 rounded hover:bg-gray-200" %>
<% end %>   

app/views/blog_posts/show.html.erb
<%= link_to 'edit', edit_blog_post_path(@blog_post) if user_signed_in? %>

<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'tailwind', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
     
    <% if user_signed_in? %>
      <%= link_to 'New blog post', new_blog_post_path %>
      <p>Welcome, <%= current_user.email %>! <%= button_to "Logout", destroy_user_session_path, method: :delete %></p>
    <% end %>
<p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>